services:
  - type: web
    name: insurance-aggregator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn insurance_aggregator.wsgi:application
    preDeployCommand: python manage.py migrate && python manage.py create_default_superuser
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9.6"
      - key: DATABASE_URL
        fromDatabase:
          name: insurance-aggregator-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
databases:
  - name: insurance-aggregator-db
    plan: free
